### PR TITLE
ffmpeg optimization

### PR DESCRIPTION
**Pull request by Monter**
- added path correction function for ffmpeg to handle folders and filenames with special characters
- remove deprecated ffmpeg option: -deinterlace
- changed ffmpeg command syntax to speed up video thumbnail creation

### CODE REVIEW

**Comment by mjau-mjau** [comment]
Looks like a good fix. I will do some more testing before merging into next release. Thanks!

**Comment by Monter** [comment]
You're welcome :-)

**Comment by Monter** [comment]
Another useful command (see description): https://stackoverflow.com/a/19849446

**Comment by mjau-mjau** [comment]
About the `mb_escapeshellarg()` function, it's not working properly, assuming you did not test characters. You have added double quotes to the $cmd `"' . mb_escapeshellarg($path) . '"`, which means we have to escape double-quotes in the $path. In your `mb_escapeshellarg()` you are escaping single-quotes only, which shouldn't even be necessary since the path is wrapped inside "double-quotes".
```php
return "" . str_replace("'", "'\"'\"'", $arg) . "";
```
I'm actually not sure what the above is doing, but surely `'` could just be escaped with `\'`. Anyway, we need to escape double quotes instead:
Changed to:
```php
return str_replace('"', '\"', $arg);
```
Tested successfully with file names including single-quotes, double-quotes, multi-byte characters, empty spaces and all other suspicious characters:
```
zz "ZH"你好世界'æøå'Γειά σου Κόσμε.mp4
zz !@~#$%^&*().df"h"-'j'[]{}.mp4
```
I'm still not convinced this is better than using PHP [escapeshellarg()](https://www.php.net/manual/en/function.escapeshellarg.php), which was made specifically for this, as I can't see any problems locally and nobody else reported any problems after correcting locale. I suppose if just escaping "quotes" works in all cases, it's the best solution.

**Comment by mjau-mjau** [comment]
**Pending fix**
Since the `$path` is now wrapped inside "quotes", we really only need to escape double quotes so that `"path/to/v"ide"o.mp4"` becomes `"path/to/v\"ide\"o.mp4"`. Should not be necessary to escape any other characters.

The performance is looking good thanks. Pending fix:
```php
$cmd = escapeshellarg(config::$config['video_ffmpeg_path']) . ' -ss 3 -t 1 -hide_banner -i "' . str_replace('"', '\"', $path) . '" -vframes:v 1 -an -vf "thumbnail,scale=480:320:force_original_aspect_ratio=increase,crop=480:320" -r 1 -y -f mjpeg "' . $cache . '" 2>&1';
```

**Comment by Monter** [comment]
> " assuming you did not test characters"
I have a request - let's focus on the facts, not on guesswork. Thanks.

I tested my patch both on special characters, as well as on spaces in the names of files and folders, and on single quotation marks. Double quotation marks for folder and file names, and many systems do not accept them. Such characters should be filtered, iMHO.
In the patch [https://github.com/mjau-mjau/files.photo.gallery/pull/12/commits/d051275431dd469f2dc2929617fffeb309f58ece](pull 12) I also closed `$patch` inside "quotes" and `str_replace` itself did not work for me.

**Comment by mjau-mjau** [comment]
> I have a request - let's focus on the facts, not on guesswork. Thanks.

I'm just updating the post. Surely you must understand that your fix doesn't work on file names that include double-quotes?

> Double quotation marks for folder and file names are prohibited, and many systems do not accept them. Such characters should be filtered, iMHO.

What do you mean "filtered"? This is a user app and it shouldn't break on characters that some users may include in file names. Besides, where does it say that quotes are not allowed in file names? Finally, if we knew all file names were without quotes, then why escape in the first place? It would be sufficient to enclose `$path` inside "quotes".

> I also closed `$path` inside "quotes"

Yes, and this is updated. By adding $path inside "quotes" means that double-quotes are the only characters we need to escape.

> and `str_replace` itself did not work for me.

Well, you must have had a typo, because there is no need to make a separate function for a simple `str_replace()`.

Thanks for all the help!

**Comment by Monter** [comment]
Again: double-quotes are not allowed on many systems (especially Windows and many network services, Internet drives, etc.) and cannot appear in folder and file names. That's why I haven't tested it, because there is no such need - you should avoid using them.
Is your gallery supposed to work properly on all systems, or only on some? ;-)

Enclosing a variable in quotation marks (for example, to handle spaces in names) and the presence of such a character, for example, in the middle of a file or folder name, are two different things.

Just `str_replace` failed for me, I don't know why (ffmpeg returns very laconic messages, I was just relying on the log showing the wrong path to the file it was supposed to create a thumbnail from). Probably there were characters typical of my native language and spaces used in the names of the files and folders making up the path to create the thumbnail.

> "Well, you must have had a typo..."

Sorry, if you know better than me what I'm doing, this discussion is a bit pointless :-)

**Comment by mjau-mjau** [comment]
Ok. Anyway, this is the new one-liner for next update unless anyone has any objections:
```php
$cmd = escapeshellarg(config::$config['video_ffmpeg_path']) . ' -ss 3 -t 1 -hide_banner -i "' . str_replace('"', '\"', $path) . '" -vframes:v 1 -an -vf "thumbnail,scale=480:320:force_original_aspect_ratio=increase,crop=480:320" -r 1 -y -f mjpeg "' . $cache . '" 2>&1';
```

**Pull request closed without merging**
